// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgG9u9u928qJ2yhxNozC8_NtiXwYeRQG0',
    appId: '1:529574008904:web:a9a50588817ebc5e42e07d',
    messagingSenderId: '529574008904',
    projectId: 'marinakamapps',
    authDomain: 'marinakamapps.firebaseapp.com',
    storageBucket: 'marinakamapps.appspot.com',
    measurementId: 'G-ELJ2JMMXYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIA_kdDLC9I4UJDeDDLNuy-aWCMiZnFBE',
    appId: '1:529574008904:android:bde62c95c338b3e242e07d',
    messagingSenderId: '529574008904',
    projectId: 'marinakamapps',
    storageBucket: 'marinakamapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVU_DcAAqU82aQFny0Gh3hLXBa3ZNy2Dk',
    appId: '1:529574008904:ios:9a0b0821ca978fef42e07d',
    messagingSenderId: '529574008904',
    projectId: 'marinakamapps',
    storageBucket: 'marinakamapps.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );
}
